### PR TITLE
85 fix hw4 silent failure

### PR DESCRIPTION
**Pull request by zhangaaron**
Fixes problem in saas_web_steps and adds regression test to fix silent failure

### CODE REVIEW

**Comment by tansaku** [comment]
great work @zhangaaron - so does this resolve the issue now?

**Comment by tansaku** [comment]
I'm getting what might be a related error in my attempt to use Travis Tokens so that we really hit our other private repos for testing:

```
[tansaku@Samuels-MBP:~/Documents/GitHub/saasbook/rag (70_testing_with_secure_solutions)]$ 
→ be cucumber features/autograder_xqueue_stubbed.feature:47
Feature: Autograder configured to accept student submissions from edX and grade them
  As an instructor
  So that I can give feedback to my students on their code responses
  I want to be able to create a code submission page in edX and grade it using rag

  @require_net_connect
  Scenario: student submits a HW4                                      # features/autograder_xqueue_stubbed.feature:47
    Given I set up a test that requires internet connection            # features/step_definitions/adapter_x_queue_steps.rb:24
    Given an XQueue that has submission "hw4_submission.json" in queue # features/step_definitions/adapter_x_queue_steps.rb:28
      ["http://www.fakedownload.com/hw4.zip"]
      register_uri for : http://www.fakedownload.com/hw4.zip
    And has been setup with the config file "conf.yml"                 # features/step_definitions/adapter_x_queue_steps.rb:44
Submission message after grade: Your submission was recorded at 2010-06-19 18:52:28 +0100 : submission is on time.
Score: 0/100
There was a fatal error with your submission. It either timed out or caused an exception.
    Then I should receive a grade of "100" for my assignment           # features/step_definitions/adapter_x_queue_steps.rb:49
      expected: == 100.0
           got:    0.0 (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/adapter_x_queue_steps.rb:57:in `/^I should receive a grade of "(.*?)" for my assignment$/'
      features/autograder_xqueue_stubbed.feature:51:in `Then I should receive a grade of "100" for my assignment'

Failing Scenarios:
cucumber features/autograder_xqueue_stubbed.feature:47 # Scenario: student submits a HW4

1 scenario (1 failed)
4 steps (1 failed, 3 passed)
0m20.138s
```

or maybe it has nothing to do with it - I wonder if it's because something is being cached ...

**Comment by tansaku** [comment]
@zhangaaron - I notice that you were experimenting with this branch on the production grader?  We do have several SPOCs using that grader - I wonder if you could run experiments like that on the staging grader?

We're having a problem with hw4 submissions that include factory girl that were fine in the past ... we've just got a fix working on the staging grader ... and would like to get that live on the production grader but I'm worried about stomping on your experiment.

Let's talk about how we coordinate the use of production and staging before we make any more changes perhaps?  Maybe you could set up another box for develop work ...

**Comment by zhangaaron** [comment]
I deployed this onto the production grader because it's being currently used in the class.

**Comment by zhangaaron** [comment]
Perhaps we can merge both onto master and then deploy live again. Not ideal to deploy right away but I was on a deadline and I did some basic testing

**Comment by tansaku** [comment]
@zhangaaron even on a deadline it's probably sensible to test on the staging grader before taking something live.  You can always point a single assignment page in edX to a different instance as well. i.e. deliver the change for one assignment without affecting everyone else.

The difficulty is that there are several other institutions using the grader as well as Berkeley so we need to agree on a deployment process to make sure we serve everyone equally.

In the first instance do you have access to the staging grader?  Can you go ahead and create a develop grader instance?

* https://devcenter.heroku.com/articles/pipelines
* https://en.wikipedia.org/wiki/Deployment_environment

I've got it on my todo list to write up a process for this, but it's all academic if it's not something that fits into your workflow ...

**Comment by zhangaaron** [comment]
That's a good point. I don't have access to the staging grading I believe, I only see two autograders in the EC2 console that are both production (one is backup, started in December, which I've been primarily modifying)

I don't know if I have enough time to do that, I've been spreading myself kind of thin since this autograder work is now part of my GSI responsibilities.

**Comment by tansaku** [comment]
@zhangaaron I've just updated the names for the graders:

!(prod and stag graders)[https://www.dropbox.com/s/hgox95ksrlzphle/Screenshot%202016-03-22%2010.48.32.png?dl=1]

They were out of date - the one you've been updating is not the backup one, it's production.  It's the one I started in December when everything was falling apart.

The staging grader uses the same key so you should have access to it.  Note that I currently have production for SUNY Binghamton hitting the staging grader to get round the issue with factory girl, so we are still in a messy setup, and we need to be careful about making modifications.

I'd say we really need a develop box for experiments, and then we can get production locked to master and use staging for debugging production failures.

It was the process of deploying a 2nd grader that let me to generating those various issues about missing documentation relating to setup.  You've been saying for a while you'd get that documentation updated.  I was thinking that deploying a develop grader would help you ensure that the documentation for grader deploy was up to date and accurate ...

**Comment by tansaku** [comment]
I think I fixed this in 8_expose_feature_grader_exceptions

**Pull request closed without merging**
