### PR TITLE
adds gems for oob assignment

### LINKED ISSUE #66: Allow grading of OOB assignment
Two issues here:

1) new gems required #58
2) support files required #60

We can hack this short term by adding gems and support files directly to grader

### PR DESCRIPTION
**Pull request by tansaku**
these are the changes I made on the production grader to support OOB grading - I also note that the production grader seems to have the origin set to Aaron's repo ...

fixes #66

### CODE REVIEW

**Comment by tansaku** [comment]
Fixes #66

For completeness I've added in the support files that are also necessary for this to work.

**Comment by tansaku** [comment]
@zhangaaron do you want to check this over before its merged?

**Comment by zhangaaron** [comment]
I'm unfamiliar with OoB assignment but it looks good.

**Comment by tansaku** [comment]
@zhangaaron are you online right now - want to come in slack and talk?

**Comment by tansaku** [comment]
thanks for merging this @zhangaaron, just checking though - you understand how ideally we shouldn't need new files and gems in the grader to support a new assignment right?  see issues #58 and #60

**Pull request merged**
