### PR TITLE
first stab at a test to wrap the stuck hw4

### LINKED ISSUE #67: HW4 causing the grader to crash
During the MOOC of fall 2015 HW4 submissions appeared to cause the grader to crash hard such that it required restarting.

It would be good to address this before the current round of SPOCs get to that assignment.

It seems like we would need a load testing harness to simulate the conditions that caused the problem

### PR DESCRIPTION
**Pull request by tansaku**
fixes #67

### CODE REVIEW

**Comment by tansaku** [comment]
@zhangaaron check this out - I've grabbed a student submission that appears to have caused a grader hang, and it appears to hang locally, i.e. we now have an acceptance test that allows us to study the issue independently of the live grader.

I have to go offline now, but if you can look at this and perhaps get further into where the freeze is coming from that would be great and I'll pick up from where you leave off tomorrow

**Comment by zhangaaron** [comment]
Best guess: timeout is not working properly. here is a stacktrace from when I killed a hung grading process. `/home/ubuntu/rag/lib/auto_grader.rb:78:in `wait': Interrupt
        from /home/ubuntu/rag/lib/auto_grader.rb:78:in `block in run_in_subprocess'
        from /home/ubuntu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
        from /home/ubuntu/rag/lib/auto_grader.rb:77:in `run_in_subprocess'
        from /home/ubuntu/rag/lib/graders/feature_grader/hw4_grader.rb:54:in `grade'
        from /home/ubuntu/rag/lib/submission/base.rb:20:in `handle_submission'
        from /home/ubuntu/rag/lib/submission/polling.rb:19:in `block in run'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `loop'
        from /home/ubuntu/rag/lib/submission/polling.rb:17:in `run'
        from run_autograder.rb:27:in `<main>'
`

**Comment by zhangaaron** [comment]
Timeout is a gem for killing processes. You can find the code in /lib/autograder.rb#run_in_subprocess. I had either a RSpec or cucumber test for ensuring timeout was working, but that wasn't used for the HW4 grader so it seems like there might be a weird interaction with HW4 grader and Timeout.. perhaps because HW4 spawns it's own subprocesses? Best guesses here, unfortunately I don't have much time to work on this this week.

**Comment by tansaku** [comment]
thanks, that's good to know.  I am analyzing with the debugger, and so far I have narrowed down to this point in the code:

```
[327, 336] in /Users/tansaku/Documents/Github/saasbook/rag/lib/graders/feature_grader/hw4_grader.rb
   327:       [0,0]
   328:     end
   329: 
   330:     def time_operation(name=nil)
   331:       start_time = Time.now.to_f
=> 332:       yield
   333:       end_time = Time.now.to_f
   334:       # TODO: Make this a debug mode setting
   335:       logger.debug "#{name}: #{end_time - start_time}s"
   336:     end
(byebug) n
```

which came from 

```
[82, 91] in /Users/tansaku/Documents/Github/saasbook/rag/lib/graders/feature_grader/hw4_grader.rb
   82:           setup_rails_app(env)
   83:         end
   84:         separator = '-'*40  # TODO move this
   85: 
   86: 
=> 87:         time_operation 'student tests' do
   88:           log separator
   89:           log "Running student tests found in features/ spec/:"
   90:           check_student_tests(env)
   91:           log separator
(byebug) s
```

the logging is not helping me as the freeze is hanging everything ... I wonder if there's a way to auto flush to the log on each statement ... anyway ... I also notice that the @timeout variable does not appear to be set ...

**Comment by tansaku** [comment]
okay, so this grades a previously sticking assignment correctly on the staging grader - however we need to merge in master to make sure we don't lose the ability to grader OOB assignments

**Comment by tansaku** [comment]
hmm, had to up timeout to 40 seconds on staging grader in order to pass the correct solution to HW4

**Comment by tansaku** [comment]
had to set even higher on production grader - timeout at 60 secs

**Comment by zhangaaron** [comment]
it sets @timeout=20 in the inherited base autograder class. But that was probably too low so good to know. Does this fix the issue now?

**Comment by zhangaaron** [comment]
This seemed to work, was it really just an issue with the timeout variable?? Going to merge it now and update production autograder because we are having huge problems on HW4 with this issue.

**Comment by zhangaaron** [comment]
Actually I noticed you already added a timeout = 60 in the production autograder. I just overwrote it with the master branch. Hopefully that is OK.

**Comment by zhangaaron** [comment]
Set back to timeout = 60 in production, saw your comment.

**Comment by tansaku** [comment]
> it sets @timeout=20 in the inherited base autograder class. 

It does, but `super` is not called in the hw4_grader so the timeout was never set - it was nil and so hw4's that got stuck were never terminating

> But that was probably too low so good to know. Does this fix the issue now?

possibly although the timeout might need to be even higher than 60 seconds

> Actually I noticed you already added a timeout = 60 in the production autograder. I just overwrote it with the master branch. Hopefully that is OK.

we'll need to keep monitoring I think, and also agree on an appropriate flow for changes to production so we don't step on each other toes.  I'll try to write some more on that soon.

**Pull request merged**
